services:
  # User Service
  user-service:
    build: ./UserService
    container_name: user-service
    env_file:
      - .env
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:1111@user-db:5432/user_service_db
      - FLASK_APP=main.py
    depends_on:
      user-db:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  user-db:
    image: postgres:15
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: user_service_db
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Music Service
  music-service:
    build: ./MusicService
    container_name: music-service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://postgres:1111@music-db:5432/music_service_db
    depends_on:
      music-db:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  music-db:
    image: postgres:15
    container_name: music-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: music_service_db
    ports:
      - "5434:5432"
    volumes:
      - music_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Recommendation Service
  recommendation-service:
    build: ./RecommendationService
    container_name: recommendation-service
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://postgres:1111@recommendation_db:5432/recommendation_service_db
    depends_on:
      recommendation_db:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  recommendation_db:
    image: postgres:15
    container_name: recommendation_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: recommendation_service_db
    ports:
      - "5435:5432"
    volumes:
      - recommendation_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Ai Service
  ai-service:
    build: ./AiService
    container_name: ai-service
    ports:
      - "5004:5004"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Gateway
  gateway:
    build: ./Gateway
    container_name: gateway
    env_file:
      - .env
    ports:
      - "5005:5005"
    depends_on:
      - user-service
      - music-service
      - recommendation-service
      - ai-service
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  user_db_data:
  music_db_data:
  recommendation_db_data: