services:
  # User Service
  user-service:
    build: ./UserService
    container_name: user-service
    ports:
      - "5001:5001"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:1111@user-db:5432/user_service_db
    depends_on:
      - user-db

  user-db:
    image: postgres:15
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: user_service_db
    ports:
      - "5433:5432"
    volumes:
      - user_db_data:/var/lib/postgresql/data

  # Music Service
  music-service:
    build: ./MusicService
    container_name: music-service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_URL=postgresql://postgres:1111@music-db:5432/music_service_db
    depends_on:
      - music-db

  music-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: music_service_db
    ports:
      - "5434:5432"
    volumes:
      - music_db_data:/var/lib/postgresql/data

  # Recommendation Service
  recommendation-service:
    build: ./RecommendationService
    container_name: recommendation-service
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://postgres:1111@recommendation_db:5432/recommendation_service_db
    depends_on:
      - recommendation_db

  recommendation_db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: recommendation_service_db
    ports:
      - "5435:5432"
    volumes:
      - recommendation_db_data:/var/lib/postgresql/data

  # Ai Service
  ai-service:
    build: ./AiService
    container_name: ai-service
    ports:
      - "5004:5004"
    # environment:
    #   - DATABASE_URL=postgresql://postgres:1111@localhost:5432/recommendation_service_db
    # depends_on:
    #   - recommendation_db

  # Gateway
  gateway:
    build: ./Gateway
    ports:
      - "5005:5005"
    depends_on:
      - user-service
      - music-service
      - recommendation-service
      - ai-service

volumes:
  user_db_data:
  music_db_data:
  recommendation_db_data:
