"""Made models more universal

Revision ID: 1d9168b3cd0d
Revises: b77e2138241b
Create Date: 2025-06-03 19:03:17.770678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9168b3cd0d'
down_revision = 'b77e2138241b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'media_type', name='_media_stats_uc')
    )
    op.drop_table('track_stats')
    op.drop_table('playlist_stats')
    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('media_type', sa.String(), nullable=False))
        batch_op.drop_column('track_id')

    with op.batch_alter_table('listening_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('media_type', sa.String(), nullable=False))
        batch_op.drop_column('track_id')

    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('media_type', sa.String(), nullable=False))
        batch_op.drop_column('playlist_id')
        batch_op.drop_column('track_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('playlist_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_id')

    with op.batch_alter_table('listening_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_id')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_id')

    op.create_table('playlist_stats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('playlist_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('view_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='playlist_stats_pkey'),
    sa.UniqueConstraint('playlist_id', name='playlist_stats_playlist_id_key')
    )
    op.create_table('track_stats',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('track_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('play_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='track_stats_pkey'),
    sa.UniqueConstraint('track_id', name='track_stats_track_id_key')
    )
    op.drop_table('media_stats')
    # ### end Alembic commands ###
