"""Add playlist_id to recommendations

Revision ID: b77e2138241b
Revises: c6c0ee7535ad
Create Date: 2025-05-25 19:25:10.406841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77e2138241b'
down_revision = 'c6c0ee7535ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playlist_id', sa.UUID(), nullable=True))
        batch_op.alter_column('track_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('track_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('playlist_id')

    # ### end Alembic commands ###
