"""Initial migration

Revision ID: 094be7efa36c
Revises: 493276202591
Create Date: 2025-05-26 02:52:52.519354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '094be7efa36c'
down_revision = '493276202591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('performers', schema=None) as batch_op:
        batch_op.drop_index('performer_search_idx', postgresql_using='gin')
        batch_op.drop_column('search_vector')

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.drop_index('playlist_search_idx', postgresql_using='gin')
        batch_op.drop_column('search_vector')

    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index('track_search_idx', postgresql_using='gin')
        batch_op.drop_column('search_vector')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
        batch_op.create_index('track_search_idx', ['search_vector'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('playlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
        batch_op.create_index('playlist_search_idx', ['search_vector'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('performers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
        batch_op.create_index('performer_search_idx', ['search_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###
