"""Added files directly instead of path in model

Revision ID: 233e442d2741
Revises: 97e9fcaf4d0c
Create Date: 2025-05-31 15:11:59.779945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233e442d2741'
down_revision = '97e9fcaf4d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stream_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###
